import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Wireless Noise-Cancelling Headphones',
    slug: 'wireless-noise-cancelling-headphones',
    shortDescription: 'Premium over-ear headphones with active noise cancellation.',
    description: 'Premium over-ear headphones with active noise cancellation and 30-hour battery life. Experience music like never before.',
    price: 3500,
    salePrice: 2999,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80'],
    category: 'Electronics',
    rating: 4.8,
    reviewCount: 124,
    soldCount: 850,
    discountPercent: 14,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Minimalist Leather Wallet',
    slug: 'minimalist-leather-wallet',
    shortDescription: 'Slim, RFID-blocking genuine leather wallet.',
    description: 'Slim, RFID-blocking genuine leather wallet with space for 6 cards and cash. Perfect for everyday use.',
    price: 1200,
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80'],
    category: 'Accessories',
    rating: 4.5,
    reviewCount: 89,
    soldCount: 340,
  },
  {
    id: '3',
    title: 'Smart Fitness Watch',
    slug: 'smart-fitness-watch',
    shortDescription: 'Track your heart rate, steps, and sleep.',
    description: 'Track your heart rate, steps, and sleep with this water-resistant smartwatch. Stay connected and healthy.',
    price: 2500,
    salePrice: 1999,
    images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80'],
    category: 'Electronics',
    rating: 4.2,
    reviewCount: 210,
    soldCount: 1200,
    discountPercent: 20,
    isFeatured: true,
  },
  {
    id: '4',
    title: 'Organic Cotton T-Shirt',
    slug: 'organic-cotton-t-shirt',
    shortDescription: 'Ultra-soft, ethically made organic cotton t-shirt.',
    description: 'Ultra-soft, ethically made organic cotton t-shirt. Available in multiple colors and fits perfectly.',
    price: 500,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80'],
    category: 'Clothing',
    rating: 4.9,
    reviewCount: 56,
    soldCount: 890,
  },
  {
    id: '5',
    title: 'Stainless Steel Water Bottle',
    slug: 'stainless-steel-water-bottle',
    shortDescription: 'Double-wall vacuum insulated water bottle.',
    description: 'Double-wall vacuum insulated water bottle. Keeps drinks cold for 24 hours or hot for 12 hours.',
    price: 800,
    salePrice: 650,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80'],
    category: 'Home & Kitchen',
    rating: 4.7,
    reviewCount: 342,
    soldCount: 2100,
    discountPercent: 18,
  },
  {
    id: '6',
    title: 'Ceramic Coffee Mug',
    slug: 'ceramic-coffee-mug',
    shortDescription: 'Handcrafted ceramic mug with a unique glaze pattern.',
    description: 'Handcrafted ceramic mug with a unique glaze pattern. Microwave and dishwasher safe.',
    price: 450,
    images: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80'],
    category: 'Home & Kitchen',
    rating: 4.4,
    reviewCount: 28,
    soldCount: 150,
  }
];
